---
# tasks file for deploy-hub-router
- name: Update repo cache
  become: yes
  apt:
    update_cache: yes

- name: Install dependencies
  become: yes
  apt:
    name:
      - wireguard
      - fping
      - iperf3
    state: latest

- name: Kill any existing nexd process from previous runs
  shell: |
    sudo killall nexd 2> /dev/null
  ignore_errors: yes

# Optionally clean all remnants of a previous run (the agent will do this as well)
#- name: Delete wg0
#  become: yes
#  shell: |
#    sudo ip link del wg0
#  ignore_errors: yes

- name: Delete hosts file
  become: yes
  shell: |
    sudo rm -rf /etc/hosts
    sudo touch /etc/hosts
  ignore_errors: yes

- name: Add controller host entry
  become: yes
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      127.0.0.1 localhost
      ::1 ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      ff02::3 ip6-allhosts
      {{ controller_address }} auth.try.nexodus.local api.try.nexodus.local try.nexodus.local

- name: Download the Nexodus Agent Binary
  shell: |
    sudo curl {{ nexodus_binary }} --output /usr/local/sbin/nexd
    sudo chmod +x /usr/local/sbin/nexd

- name: Copy the verifier script
  copy:
    src: verify-connectivity.sh
    dest: /home/{{ ansible_user }}/
    mode: '0755'

- name: Attach the Hub Router to the Controller
  become: yes
  shell: |
    NEXD_LOGLEVEL=debug nexd \
    --hub-router \
    --stun \
    --username '{{ nexodus_auth_uid }}' \
    --password '{{ nexodus_auth_password }}' \
    {{ nexodus_url }} > nexodus-logs.txt 2>&1 &
