apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: apiserver
          image: quay.io/nexodus/apiserver:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: DEBUG
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-pguser-apiserver
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: database-pguser-apiserver
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-pguser-apiserver
                  key: dbname
            - name: _DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-pguser-apiserver
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-pguser-apiserver
                  key: password
            - name: DB_SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: DB_SSLMODE
            - name: IPAM_URL
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: IPAM_URL
            - name: OIDC_URL
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: OIDC_URL
            - name: OIDC_BACKCHANNEL
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: OIDC_BACKCHANNEL
            - name: INSECURE_TLS
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: INSECURE_TLS
            - name: OIDC_CLIENT_ID_WEB
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: web-client-id
                  optional: false
            - name: OIDC_CLIENT_ID_CLI
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: cli-client-id
                  optional: false
            - name: TRACE_ENDPOINT_OTLP
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: TRACE_ENDPOINT_OTLP
            - name: TRACE_INSECURE
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: TRACE_INSECURE
            - name: FFLAG_MULTI_ORGANIZATION
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: FFLAG_MULTI_ORGANIZATION
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            periodSeconds: 5
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
      restartPolicy: Always
