apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: apiserver
    literals:
      - DEBUG=1
      - IPAM_URL=http://ipam:9090
      - OIDC_URL=https://auth.nexodus.local/realms/nexodus
      - OIDC_BACKCHANNEL=https://auth.nexodus.svc.cluster.local:8443/realms/nexodus
      - INSECURE_TLS=1
      - TRACE_ENDPOINT_OTLP=""
      - TRACE_INSECURE="1"
      - FFLAG_MULTI_ORGANIZATION=false
      - DB_SSLMODE=require
resources:
  - service.yaml
  - deployment.yaml
commonLabels:
  app.kubernetes.io/component: apiserver
  app.kubernetes.io/instance: apiserver
  app.kubernetes.io/name: apiserver
