pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=build-workflow-complete
      - label!=hold
    actions:
      merge:
        method: merge

  - name: automatic merge for main with > 1 approved reviews, all requested reviews have given feedback, not held, and CI is successful
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - base=main
      - label!=hold
      - check-success=DCO
      - or:
        - label=has-design
        - label=no-design-required
      - or:
        - label=has-docs
        - label=no-docs-required
      - or:
        # PRs that include doc changes should also pass the markdown-lint check
        - and:
          - check-success=build-workflow-complete
          - files~=\.md$
          - check-success=markdown-lint
        # PRs that do not include doc changes only need to pass the build workflow
        - and:
          - check-success=build-workflow-complete
          - -files~=\.md$
        # PRs that do not run the build workflow (e.g. docs-only changes) must have a successful markdown-lint check
        - and:
          - check-success=markdown-lint
          # Must stay in sync with the paths in .github/workflows/docs.yml and .github/workflows/build.yml
          - -files~=^(?!.*\.md$)(?!.*\.gitignore$)(?!\.vscode\/).*$
    actions:
      merge:
        method: merge

  - name: Warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}}, this pull request is now in conflict and requires a rebase."
      label:
        add:
          - needs-rebase
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - needs-rebase
