pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=build-workflow-complete
      - label!=hold
    actions:
      merge:
        method: merge
  - name: automatic merge for main with > 1 approved reviews, all requested reviews have given feedback, not held, and the build workflow is successful
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - base=main
      - label!=hold
      - check-success=build-workflow-complete
    actions:
      merge:
        method: merge
