apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nexodus
resources:
  - apiproxy
  - apiserver
  - auth
  - database
  - frontend
  - ipam
  - redis
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: nexodus
