apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nexodus
resources:
  - apiproxy
  - apiserver
  - auth
  - backend-cli
  - backend-web
  - database
  - frontend
  - ipam
commonLabels:
  app.kubernetes.io/part-of: nexodus
