apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml

configMapGenerator:
  - literals:
      - GOIPAM_PG_SSLMODE=require
    name: ipam
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: ipam
      app.kubernetes.io/instance: ipam
      app.kubernetes.io/name: ipam
