apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - issuer.yaml
  - serviceaccount.yaml
namespace: apex
configMapGenerator:
  - name: auth-config
    behavior: replace
    literals:
      - hostname=auth.apex-hosted.cloud
      - frontend-url=https://apex-hosted.cloud
  - name: realm
    behavior: replace
    files:
      - files/apex.json
patchesJson6902:
  - patch: |-
      - op: replace
        path: /data/APEX_OIDC_URL
        value: https://auth.apex-hosted.cloud/realms/apex
    target:
      kind: ConfigMap
      name: apiserver
  - patch: |-
      - op: replace
        path: /data/DOMAIN
        value: api.apex-hosted.cloud
      - op: replace
        path: /data/OIDC_PROVIDER
        value: https://auth.apex-hosted.cloud/realms/apex
      - op: replace
        path: /data/ORIGINS
        value: https://apex-hosted.cloud
      - op: replace
        path: /data/REDIRECT_URL
        value: https://apex-hosted.cloud/#/login
    target:
      kind: ConfigMap
      name: backend-web
  - patch: |-
      - op: replace
        path: /data/DOMAIN
        value: https://api.apex-hosted.cloud
      - op: replace
        path: /data/OIDC_PROVIDER
        value: https://auth.apex-hosted.cloud/realms/apex
    target:
      kind: ConfigMap
      name: backend-cli
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.apex-hosted.cloud
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.apex-hosted.cloud
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: apiproxy
  - patch: |-
      - op: add
        path: /spec/template/spec/serviceAccountName
        value: apex-serviceaccount
    target:
      kind: Deployment
      name: apiproxy
  - patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
      - op: remove
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1ssl-passthrough
      - op: replace
        path: /spec/rules/0/host
        value: auth.apex-hosted.cloud
      - op: replace
        path: /spec/rules/0/http/paths/0/pathType
        value: ImplementationSpecific
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: ''
    target:
      kind: Ingress
      name: auth
  - patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: auth.apex-hosted.cloud
      - op: replace
        path: /spec/issuerRef/name
        value: letsencrypt
    target:
      kind: Certificate
      name: apex-auth-cert
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: apex-hosted.cloud
      - op: replace
        path: /spec/tls/0/hosts/0
        value: apex-hosted.cloud
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: frontend

images:
  - name: quay.io/apex/apiserver
    newTag: 6b7371ff93d476297b4cdb9fa38860162d93ed43
  - name: quay.io/apex/frontend
    newTag: 6b7371ff93d476297b4cdb9fa38860162d93ed43
  - name: quay.io/apex/go-ipam
    newTag: 6b7371ff93d476297b4cdb9fa38860162d93ed43
