apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: backend-web
    literals:
      - DEBUG=1
      - OIDC_PROVIDER=https://auth.nexodus.local/realms/nexodus
      - OIDC_BACKCHANNEL=https://auth.nexodus.svc.cluster.local:8443/realms/nexodus
      - INSECURE_TLS=1
      - DOMAIN=api.nexodus.local
      - REDIRECT_URL=https://nexodus.local/#/login
      - ORIGINS=https://nexodus.local
      - BACKEND=http://apiserver:8080
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/component: backend-web
  app.kubernetes.io/instance: backend-web
  app.kubernetes.io/name: backend-web
