apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-providers
  namespace: nexodus-qa
spec:
  encryptedData:
    GOOGLE_CLIENT_ID: AgBbslLPwPu9ZRcA99M+KWwjodrfc1WoMN0pRhJKdMtiUXZWGZeJeXGpyb0ww3ne3csgfNjggDl3rcdeegP2303U5Xqx6Vh8El5J6UMwYCtp8nKnfze63uZGI2MAftfiQlo9J2qhMul8xW91L1OztAa2no4ajQIZ0V1o2ufFSTzWGHjX6Jhp6+KICeBCyGpeYo+gMIn6riiINWi7Q+vA3bIAqluFu6LI6eqDpeJLu4A7LzUozG2nbhRg3Rrba9ypyDRMGOivTd0amrA+HGaPp90FLYDeLvprdhzsll2jzH5GwnFk09NhG966q9kjEpNtUHDX4iKgd7G9bq7bEAPwNjUrFU+4YPc5q9xyTdIhfdn7FRC3R4DZEJc8XXkxgOyKOjbFErma27aQy25FOgPXbnj0REpL24viD7LzKhUR0ZhtR4XTxXyzccEnU/Km+V+rxYUhaVMfOKvyyEs9RzSaEQPBbK2ye2o2iO9Mog6L3hslFWkeBJA6R0Ti4S2os+5KYDDe0bqodHyddve4+syWrtHgeoqEy1iGwGTJzRZs3eptlQqchEWQjlUb+ziBtqunegYmYKplVZ8ibFmqAfF0FA9K0DWPIVClO/TEP7XM/WYHq2wCdG3Z25ZSMHbYZn/ic5pOoVjVrMyj9xMmWNA2/sUcrwgKWtwawuYiUEinLDSe1vE8LW0gaFQ3hu+4oPsBZvrKKRdi0Ux73ZD7TgTOtouhzyavRfDaQg1s0iyaWgSyt+BYq529sxMIPQDAic0i2Wj/cVzlM4IOnETy8soOBs9/mBmHauD+pns=
    GOOGLE_CLIENT_SECRET: AgBcmrMteWZTku7rDWY8oxvUpcoEOqmI3cTrv/vasQZSlI647GNme9j/aZHjWZM9dvEfJYa4Sz5DxoWY9M9cMlC4P2N9JJp8lnwkq/iatDs30DDA5qRBjMpT4RPgG36HCOLvPDIhoIHrN5TWmexdjCNjIRKFIbFI+HJ3EE/k9Zxm7wLSgVZX5RFzBWuf8ngKmhmJ58taLYUZDGghi+sntexgJHi7yOPs6dkX69zmQTFOu4I+oGQd/k/mAJxTxENDp6SnG4AMQuM6iK8BPSmjeyfazE2XXDX8ZaweiUGEfZU2UjC7PDP0yiw1TkWJniqgANahVujD2iVS7LMxQ/+CyyGOBfSlVBYWlN926HUZPSIA6OwRtHL0y1juv+T+Y5DX4/bT4aXl2odqVnWrGjtR0pTNQNHgE5lZKCJ4UXK91GjBW0mVRjhxzMLutR2iJPS+/ewVs1rlRgDH28m0h0S41TAneMRkaWX1IWQUSCNovmHwRyflI9rllq1GJGEgyAHgo/EkYAujc1D/bofm664C0pKSF87WUpcxe+IPYeMlB0FnRBCZoeFU2VbHqPLUaYX+avCMB4zN8qeAdJqdtijQHLoz7y9l7Gidt9VPeSLOln2Z5w3rDbSUuyKDmxdGTIPPawIcTqqyeXopj9DpEMR51uRkRySFkb1QCC2iPyTgacs5wWLvvddQ5YKnCIXLCGRNiEqlZ8oJc48Uzify151/di8GioaVYVY/ZWXhc2jePwBpkG1s0A==
  template:
    metadata:
      creationTimestamp: null
      name: auth-providers
      namespace: nexodus-qa

