apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qa-apiproxy
  labels:
    team: nexodus
spec:
  namespaceSelector:
    matchNames:
      - nexodus-qa
  selector:
    matchLabels:
      app.kubernetes.io/name: apiproxy
  endpoints:
    - port: admin
