apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: qa-apiserver
  namespace: nexodus-monitoring
  labels:
    team: nexodus
spec:
  namespaceSelector:
    matchNames:
      - nexodus-qa
  selector:
    matchLabels:
      app.kubernetes.io/name: apiserver
  endpoints:
    - port: web
