apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - apiproxy-service-monitor.yaml
  - apiserver-service-monitor.yaml
# TODO: Add patches to override the URLs in ROSA
