apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../dev
  - cockroach.yaml

namespace: nexodus

secretGenerator:
  - literals:
      - dbname=ipam
      - host=cockroachdb-public
      - password=password
      - port=26257
      - user=ipam
    name: database-pguser-ipam
  - literals:
      - dbname=apiserver
      - host=cockroachdb-public
      - password=password
      - port=26257
      - user=apiserver
    name: database-pguser-apiserver
  - literals:
      - host=postgres
      - port=5432
      - user=keycloak
      - password=password
      - dbname=keycloak
    name: database-pguser-keycloak

configMapGenerator:
  - behavior: merge
    literals:
      - GOIPAM_PG_SSLMODE=disable
    name: ipam
  - behavior: merge
    literals:
      - NEXAPI_DB_SSLMODE=disable
    name: apiserver

patches:
  - patch: |-
      $patch: delete
      apiVersion: postgres-operator.crunchydata.com/v1beta1
      kind: PostgresCluster
      metadata:
        name: database
