---
- name: Initialize the PR or Branch on the api-server
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Initialize the PR or Branch on the api-server
      shell: |
        curl https://nexodus-io.s3.amazonaws.com/ec2-e2e/init-pr-e2e.sh -o ./init-pr-e2e.sh
        chmod +x ./init-pr-e2e.sh
        ./init-pr-e2e.sh "{{ pr_or_branch }}" 2>&1 | tee e2e-action.log
      register: result
      delegate_to: "{{ target_host }}"
