apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apiserver-dashboard.yaml
  - datasource.yaml
  - grafana.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: grafana
      app.kubernetes.io/instance: grafana
      app.kubernetes.io/name: grafana
