apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nexodus-auth-cert
spec:
  secretName: nexodus-auth-cert
  duration: 2160h  # 90d
  renewBefore: 360h  # 15d
  subject:
    organizations:
      - nexodus
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - auth.try.nexodus.local
  issuerRef:
    name: nexodus-issuer
    kind: Issuer
