apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
configMapGenerator:
  - literals:
      - hostname=auth.try.nexodus.127.0.0.1.nip.io
      - frontend-url=https://try.nexodus.127.0.0.1.nip.io
    name: auth-config
  - files:
      - files/nexodus.json
    name: realm
secretGenerator:
  - literals:
      - keycloak-admin-password=floofykittens
      - web-client-id=nexodus-web
      - web-client-secret=dhEN2dsqyUg5qmaDAdqi4CmH
      - cli-client-id=nexodus-cli
    name: auth-secrets
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: auth
      app.kubernetes.io/instance: auth
      app.kubernetes.io/name: auth
