apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apiserver
  labels:
    team: nexodus
spec:
  namespaceSelector:
    matchNames:
      - nexodus
  selector:
    matchLabels:
      app.kubernetes.io/name: apiserver
  endpoints:
    - port: web
