apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nexodus-monitoring
resources:
  - apiproxy-service-monitor.yaml
  - apiserver-service-monitor.yaml
  - jaeger.yaml
  - prometheus-service.yaml
  - grafana.yaml
  - grafana-datasource.yaml
  - grafana-dashboard.yaml
