apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: nexodus-monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: nexodus-monitoring
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: nexodus
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
