#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: 46a32cbb669b5b14d71f12eb55904101f07e7bed
  - name: quay.io/nexodus/envsubst
    newTag: 46a32cbb669b5b14d71f12eb55904101f07e7bed
  - name: quay.io/nexodus/frontend
    newTag: 46a32cbb669b5b14d71f12eb55904101f07e7bed
  - name: quay.io/nexodus/go-ipam
    newTag: 46a32cbb669b5b14d71f12eb55904101f07e7bed
