#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: cb0ab241d1fb133c731495a3d3c183b062543f0a
  - name: quay.io/nexodus/envsubst
    newTag: cb0ab241d1fb133c731495a3d3c183b062543f0a
  - name: quay.io/nexodus/frontend
    newTag: cb0ab241d1fb133c731495a3d3c183b062543f0a
  - name: quay.io/nexodus/go-ipam
    newTag: cb0ab241d1fb133c731495a3d3c183b062543f0a
