#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 36606fb45ace7971b58d6ef262b85ac2a9851a74
  - name: quay.io/nexodus/envsubst
    newTag: 36606fb45ace7971b58d6ef262b85ac2a9851a74
  - name: quay.io/nexodus/frontend
    newTag: 36606fb45ace7971b58d6ef262b85ac2a9851a74
  - name: quay.io/nexodus/go-ipam
    newTag: 36606fb45ace7971b58d6ef262b85ac2a9851a74
