#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: a83b810e1db29c87248a708ae60c8becd5e01f83
  - name: quay.io/nexodus/envsubst
    newTag: a83b810e1db29c87248a708ae60c8becd5e01f83
  - name: quay.io/nexodus/frontend
    newTag: a83b810e1db29c87248a708ae60c8becd5e01f83
  - name: quay.io/nexodus/go-ipam
    newTag: a83b810e1db29c87248a708ae60c8becd5e01f83
