#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 4d5cb8ab44daf8ce17cfaead0f68abea449709ef
  - name: quay.io/nexodus/envsubst
    newTag: 4d5cb8ab44daf8ce17cfaead0f68abea449709ef
  - name: quay.io/nexodus/frontend
    newTag: 4d5cb8ab44daf8ce17cfaead0f68abea449709ef
  - name: quay.io/nexodus/go-ipam
    newTag: 4d5cb8ab44daf8ce17cfaead0f68abea449709ef
