#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: c489189156866b4c3b2a42ba1c460234ad22b86d
  - name: quay.io/nexodus/envsubst
    newTag: c489189156866b4c3b2a42ba1c460234ad22b86d
  - name: quay.io/nexodus/frontend
    newTag: c489189156866b4c3b2a42ba1c460234ad22b86d
  - name: quay.io/nexodus/go-ipam
    newTag: c489189156866b4c3b2a42ba1c460234ad22b86d
