#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: cb4b422e8bc32c20caa38ab1e903b0341b713086
  - name: quay.io/nexodus/envsubst
    newTag: cb4b422e8bc32c20caa38ab1e903b0341b713086
  - name: quay.io/nexodus/frontend
    newTag: cb4b422e8bc32c20caa38ab1e903b0341b713086
  - name: quay.io/nexodus/go-ipam
    newTag: cb4b422e8bc32c20caa38ab1e903b0341b713086
