#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: fad534190577ba4e31e7cead936774ea494189f6
  - name: quay.io/nexodus/envsubst
    newTag: fad534190577ba4e31e7cead936774ea494189f6
  - name: quay.io/nexodus/frontend
    newTag: fad534190577ba4e31e7cead936774ea494189f6
  - name: quay.io/nexodus/go-ipam
    newTag: fad534190577ba4e31e7cead936774ea494189f6
