#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: ddacdd44f654b9f6214e9cdbb90380be43c190b4
  - name: quay.io/nexodus/envsubst
    newTag: ddacdd44f654b9f6214e9cdbb90380be43c190b4
  - name: quay.io/nexodus/frontend
    newTag: ddacdd44f654b9f6214e9cdbb90380be43c190b4
  - name: quay.io/nexodus/go-ipam
    newTag: ddacdd44f654b9f6214e9cdbb90380be43c190b4
