#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 26a4ecef00655405769eb13a6bf8ffaa904bc504
  - name: quay.io/nexodus/envsubst
    newTag: 26a4ecef00655405769eb13a6bf8ffaa904bc504
  - name: quay.io/nexodus/frontend
    newTag: 26a4ecef00655405769eb13a6bf8ffaa904bc504
  - name: quay.io/nexodus/go-ipam
    newTag: 26a4ecef00655405769eb13a6bf8ffaa904bc504
