#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 3e67c13b18889386c8a8d0672ae1f2515d60b7ce
  - name: quay.io/nexodus/envsubst
    newTag: 3e67c13b18889386c8a8d0672ae1f2515d60b7ce
  - name: quay.io/nexodus/frontend
    newTag: 3e67c13b18889386c8a8d0672ae1f2515d60b7ce
  - name: quay.io/nexodus/go-ipam
    newTag: 3e67c13b18889386c8a8d0672ae1f2515d60b7ce
