#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 78a86766ec43a39ab52ce5218b9d51405f9d4236
  - name: quay.io/nexodus/envsubst
    newTag: 78a86766ec43a39ab52ce5218b9d51405f9d4236
  - name: quay.io/nexodus/frontend
    newTag: 78a86766ec43a39ab52ce5218b9d51405f9d4236
  - name: quay.io/nexodus/go-ipam
    newTag: 78a86766ec43a39ab52ce5218b9d51405f9d4236
