#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 56e4b603a19b5d988f679380eb42453c290af439
  - name: quay.io/nexodus/envsubst
    newTag: 56e4b603a19b5d988f679380eb42453c290af439
  - name: quay.io/nexodus/frontend
    newTag: 56e4b603a19b5d988f679380eb42453c290af439
  - name: quay.io/nexodus/go-ipam
    newTag: 56e4b603a19b5d988f679380eb42453c290af439
