#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 2b7bc29bd3e8cb229a6ce3255eb7034259028469
  - name: quay.io/nexodus/envsubst
    newTag: 2b7bc29bd3e8cb229a6ce3255eb7034259028469
  - name: quay.io/nexodus/frontend
    newTag: 2b7bc29bd3e8cb229a6ce3255eb7034259028469
  - name: quay.io/nexodus/go-ipam
    newTag: 2b7bc29bd3e8cb229a6ce3255eb7034259028469
