#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: 19a2e14331df9d9b1d994a6e7a0475da0744d63e
  - name: quay.io/nexodus/envsubst
    newTag: 19a2e14331df9d9b1d994a6e7a0475da0744d63e
  - name: quay.io/nexodus/frontend
    newTag: 19a2e14331df9d9b1d994a6e7a0475da0744d63e
  - name: quay.io/nexodus/go-ipam
    newTag: 19a2e14331df9d9b1d994a6e7a0475da0744d63e
