#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 46da4985df58070e527b8fef23ac48b4cfb30e91
  - name: quay.io/nexodus/envsubst
    newTag: 46da4985df58070e527b8fef23ac48b4cfb30e91
  - name: quay.io/nexodus/frontend
    newTag: 46da4985df58070e527b8fef23ac48b4cfb30e91
  - name: quay.io/nexodus/go-ipam
    newTag: 46da4985df58070e527b8fef23ac48b4cfb30e91
