#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 187a74b882d90b4e955dabe74b8bac499a77a107
  - name: quay.io/nexodus/envsubst
    newTag: 187a74b882d90b4e955dabe74b8bac499a77a107
  - name: quay.io/nexodus/frontend
    newTag: 187a74b882d90b4e955dabe74b8bac499a77a107
  - name: quay.io/nexodus/go-ipam
    newTag: 187a74b882d90b4e955dabe74b8bac499a77a107
