#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: 6f82bbf6977f98f2cd4e8b75a31f1318adda436e
  - name: quay.io/nexodus/envsubst
    newTag: 6f82bbf6977f98f2cd4e8b75a31f1318adda436e
  - name: quay.io/nexodus/frontend
    newTag: 6f82bbf6977f98f2cd4e8b75a31f1318adda436e
  - name: quay.io/nexodus/go-ipam
    newTag: 6f82bbf6977f98f2cd4e8b75a31f1318adda436e
