#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 87ab5d9e70e6fe69fe8dddd29588be5c311349d0
  - name: quay.io/nexodus/envsubst
    newTag: 87ab5d9e70e6fe69fe8dddd29588be5c311349d0
  - name: quay.io/nexodus/frontend
    newTag: 87ab5d9e70e6fe69fe8dddd29588be5c311349d0
  - name: quay.io/nexodus/go-ipam
    newTag: 87ab5d9e70e6fe69fe8dddd29588be5c311349d0
