#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: f1d283e017d8e3f7fdc50362d59955b636e32900
  - name: quay.io/nexodus/envsubst
    newTag: f1d283e017d8e3f7fdc50362d59955b636e32900
  - name: quay.io/nexodus/frontend
    newTag: f1d283e017d8e3f7fdc50362d59955b636e32900
  - name: quay.io/nexodus/go-ipam
    newTag: f1d283e017d8e3f7fdc50362d59955b636e32900
