#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/monitoring
  - ../../components/limitador
patchesJson6902:
  - target:
      name: apiserver
      kind: ConfigMap
      namespace: nexodus
    patch: |-
      - op: replace
        path: /data/NEXAPI_TRACE_ENDPOINT_OTLP
        value: jaeger-collector:4317
      - op: replace
        path: /data/NEXAPI_TRACE_INSECURE
        value: "1"
images:
  - name: quay.io/nexodus/apiserver
    newTag: 1295e676cceb8acdf0196b013ea54142aafde13c
  - name: quay.io/nexodus/envsubst
    newTag: 1295e676cceb8acdf0196b013ea54142aafde13c
  - name: quay.io/nexodus/frontend
    newTag: 1295e676cceb8acdf0196b013ea54142aafde13c
  - name: quay.io/nexodus/go-ipam
    newTag: 1295e676cceb8acdf0196b013ea54142aafde13c
