#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 630773c66aa724c7456f5833eb96469ccf0be0ea
  - name: quay.io/nexodus/envsubst
    newTag: 630773c66aa724c7456f5833eb96469ccf0be0ea
  - name: quay.io/nexodus/frontend
    newTag: 630773c66aa724c7456f5833eb96469ccf0be0ea
  - name: quay.io/nexodus/go-ipam
    newTag: 630773c66aa724c7456f5833eb96469ccf0be0ea
