#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: e6f0db9bac40c7e42ed13d138808346ba3ee207e
  - name: quay.io/nexodus/envsubst
    newTag: e6f0db9bac40c7e42ed13d138808346ba3ee207e
  - name: quay.io/nexodus/frontend
    newTag: e6f0db9bac40c7e42ed13d138808346ba3ee207e
  - name: quay.io/nexodus/go-ipam
    newTag: e6f0db9bac40c7e42ed13d138808346ba3ee207e
