#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: f74e9d2f44fc6a7871edb066eba8f16e36efc4df
  - name: quay.io/nexodus/envsubst
    newTag: f74e9d2f44fc6a7871edb066eba8f16e36efc4df
  - name: quay.io/nexodus/frontend
    newTag: f74e9d2f44fc6a7871edb066eba8f16e36efc4df
  - name: quay.io/nexodus/go-ipam
    newTag: f74e9d2f44fc6a7871edb066eba8f16e36efc4df
