#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: ed65e7b9813d2f6180e868934dfb38d4e2ee75d3
  - name: quay.io/nexodus/envsubst
    newTag: ed65e7b9813d2f6180e868934dfb38d4e2ee75d3
  - name: quay.io/nexodus/frontend
    newTag: ed65e7b9813d2f6180e868934dfb38d4e2ee75d3
  - name: quay.io/nexodus/go-ipam
    newTag: ed65e7b9813d2f6180e868934dfb38d4e2ee75d3
