#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: a1dc7c5dd4ed181e5066b32dd7140633f14ae0f3
  - name: quay.io/nexodus/envsubst
    newTag: a1dc7c5dd4ed181e5066b32dd7140633f14ae0f3
  - name: quay.io/nexodus/frontend
    newTag: a1dc7c5dd4ed181e5066b32dd7140633f14ae0f3
  - name: quay.io/nexodus/go-ipam
    newTag: a1dc7c5dd4ed181e5066b32dd7140633f14ae0f3
