#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 3eba4a6bad4ac92a6157c45a2540e677bea8f542
  - name: quay.io/nexodus/envsubst
    newTag: 3eba4a6bad4ac92a6157c45a2540e677bea8f542
  - name: quay.io/nexodus/frontend
    newTag: 3eba4a6bad4ac92a6157c45a2540e677bea8f542
  - name: quay.io/nexodus/go-ipam
    newTag: 3eba4a6bad4ac92a6157c45a2540e677bea8f542
