#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 78e07962937b81c6b55e6ed22574b7316ba75c15
  - name: quay.io/nexodus/envsubst
    newTag: 78e07962937b81c6b55e6ed22574b7316ba75c15
  - name: quay.io/nexodus/frontend
    newTag: 78e07962937b81c6b55e6ed22574b7316ba75c15
  - name: quay.io/nexodus/go-ipam
    newTag: 78e07962937b81c6b55e6ed22574b7316ba75c15
