#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 1d9a1c5a4a819e70c8b7c71cf52c00248cf816d3
  - name: quay.io/nexodus/envsubst
    newTag: 1d9a1c5a4a819e70c8b7c71cf52c00248cf816d3
  - name: quay.io/nexodus/frontend
    newTag: 1d9a1c5a4a819e70c8b7c71cf52c00248cf816d3
  - name: quay.io/nexodus/go-ipam
    newTag: 1d9a1c5a4a819e70c8b7c71cf52c00248cf816d3
