#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: ebc9d3b4f055f4d1ebfd1568f5db25dd253a61c1
  - name: quay.io/nexodus/envsubst
    newTag: ebc9d3b4f055f4d1ebfd1568f5db25dd253a61c1
  - name: quay.io/nexodus/frontend
    newTag: ebc9d3b4f055f4d1ebfd1568f5db25dd253a61c1
  - name: quay.io/nexodus/go-ipam
    newTag: ebc9d3b4f055f4d1ebfd1568f5db25dd253a61c1
