#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 1cdae7a4360f7f2ef147e440308a7d305e39dc20
  - name: quay.io/nexodus/envsubst
    newTag: 1cdae7a4360f7f2ef147e440308a7d305e39dc20
  - name: quay.io/nexodus/frontend
    newTag: 1cdae7a4360f7f2ef147e440308a7d305e39dc20
  - name: quay.io/nexodus/go-ipam
    newTag: 1cdae7a4360f7f2ef147e440308a7d305e39dc20
