#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: 211cbe0c15c7f79d5179dc2a2ae23abb149b36ef
  - name: quay.io/nexodus/envsubst
    newTag: 211cbe0c15c7f79d5179dc2a2ae23abb149b36ef
  - name: quay.io/nexodus/frontend
    newTag: 211cbe0c15c7f79d5179dc2a2ae23abb149b36ef
  - name: quay.io/nexodus/go-ipam
    newTag: 211cbe0c15c7f79d5179dc2a2ae23abb149b36ef
