#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: a670df4b669e38c0cbf5f72a169d83a0294bedb5
  - name: quay.io/nexodus/envsubst
    newTag: a670df4b669e38c0cbf5f72a169d83a0294bedb5
  - name: quay.io/nexodus/frontend
    newTag: a670df4b669e38c0cbf5f72a169d83a0294bedb5
  - name: quay.io/nexodus/go-ipam
    newTag: a670df4b669e38c0cbf5f72a169d83a0294bedb5
