#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 40f1f004783c58f2ca9d4d5df967511852d72ca0
  - name: quay.io/nexodus/envsubst
    newTag: 40f1f004783c58f2ca9d4d5df967511852d72ca0
  - name: quay.io/nexodus/frontend
    newTag: 40f1f004783c58f2ca9d4d5df967511852d72ca0
  - name: quay.io/nexodus/go-ipam
    newTag: 40f1f004783c58f2ca9d4d5df967511852d72ca0
