#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 851467d582b2f4c497b01b8b565e860ebe34a41c
  - name: quay.io/nexodus/envsubst
    newTag: 851467d582b2f4c497b01b8b565e860ebe34a41c
  - name: quay.io/nexodus/frontend
    newTag: 851467d582b2f4c497b01b8b565e860ebe34a41c
  - name: quay.io/nexodus/go-ipam
    newTag: 851467d582b2f4c497b01b8b565e860ebe34a41c
