#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: e1f7d6a3648db292b50a0564085026ae61a19979
  - name: quay.io/nexodus/envsubst
    newTag: e1f7d6a3648db292b50a0564085026ae61a19979
  - name: quay.io/nexodus/frontend
    newTag: e1f7d6a3648db292b50a0564085026ae61a19979
  - name: quay.io/nexodus/go-ipam
    newTag: e1f7d6a3648db292b50a0564085026ae61a19979
