#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: abac1017f512fdfab311c46c511e2719ae3f215d
  - name: quay.io/nexodus/envsubst
    newTag: abac1017f512fdfab311c46c511e2719ae3f215d
  - name: quay.io/nexodus/frontend
    newTag: abac1017f512fdfab311c46c511e2719ae3f215d
  - name: quay.io/nexodus/go-ipam
    newTag: abac1017f512fdfab311c46c511e2719ae3f215d
