#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 63f2a48667bea303f385d3bbdaab099e99370f21
  - name: quay.io/nexodus/envsubst
    newTag: 63f2a48667bea303f385d3bbdaab099e99370f21
  - name: quay.io/nexodus/frontend
    newTag: 63f2a48667bea303f385d3bbdaab099e99370f21
  - name: quay.io/nexodus/go-ipam
    newTag: 63f2a48667bea303f385d3bbdaab099e99370f21
