#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 67f55684a1ab1fc6a52cd661b8cb5534f47f5f15
  - name: quay.io/nexodus/envsubst
    newTag: 67f55684a1ab1fc6a52cd661b8cb5534f47f5f15
  - name: quay.io/nexodus/frontend
    newTag: 67f55684a1ab1fc6a52cd661b8cb5534f47f5f15
  - name: quay.io/nexodus/go-ipam
    newTag: 67f55684a1ab1fc6a52cd661b8cb5534f47f5f15
