#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: e7406a095f658b925173afec5a4c93b71ffc2a52
  - name: quay.io/nexodus/envsubst
    newTag: e7406a095f658b925173afec5a4c93b71ffc2a52
  - name: quay.io/nexodus/frontend
    newTag: e7406a095f658b925173afec5a4c93b71ffc2a52
  - name: quay.io/nexodus/go-ipam
    newTag: e7406a095f658b925173afec5a4c93b71ffc2a52
