#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 539b6564f747fdc8320bee66986e773e54b7a399
  - name: quay.io/nexodus/envsubst
    newTag: 539b6564f747fdc8320bee66986e773e54b7a399
  - name: quay.io/nexodus/frontend
    newTag: 539b6564f747fdc8320bee66986e773e54b7a399
  - name: quay.io/nexodus/go-ipam
    newTag: 539b6564f747fdc8320bee66986e773e54b7a399
