#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/monitoring
  - ../../components/limitador
patchesJson6902:
  - patch: |-
      - op: replace
        path: /data/NEXAPI_TRACE_ENDPOINT_OTLP
        value: jaeger-collector:4317
      - op: replace
        path: /data/NEXAPI_TRACE_INSECURE
        value: "1"
    target:
      kind: ConfigMap
      name: apiserver
      namespace: nexodus
images:
  - name: quay.io/nexodus/apiserver
    newTag: f81a151eb4803f2057e99aa4652856ef63e8c2f6
  - name: quay.io/nexodus/envsubst
    newTag: f81a151eb4803f2057e99aa4652856ef63e8c2f6
  - name: quay.io/nexodus/frontend
    newTag: f81a151eb4803f2057e99aa4652856ef63e8c2f6
  - name: quay.io/nexodus/go-ipam
    newTag: f81a151eb4803f2057e99aa4652856ef63e8c2f6
