#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 04574defb549560f7a86930c197ad04fcb148d00
  - name: quay.io/nexodus/envsubst
    newTag: 04574defb549560f7a86930c197ad04fcb148d00
  - name: quay.io/nexodus/frontend
    newTag: 04574defb549560f7a86930c197ad04fcb148d00
  - name: quay.io/nexodus/go-ipam
    newTag: 04574defb549560f7a86930c197ad04fcb148d00
