#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: 216b4079baa06330bc26cc6d0ef5dce0d4f26d50
  - name: quay.io/nexodus/envsubst
    newTag: 216b4079baa06330bc26cc6d0ef5dce0d4f26d50
  - name: quay.io/nexodus/frontend
    newTag: 216b4079baa06330bc26cc6d0ef5dce0d4f26d50
  - name: quay.io/nexodus/go-ipam
    newTag: 216b4079baa06330bc26cc6d0ef5dce0d4f26d50
