#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 0b21998ef8ce86df97f278dd9fa6852779074c1b
  - name: quay.io/nexodus/envsubst
    newTag: 0b21998ef8ce86df97f278dd9fa6852779074c1b
  - name: quay.io/nexodus/frontend
    newTag: 0b21998ef8ce86df97f278dd9fa6852779074c1b
  - name: quay.io/nexodus/go-ipam
    newTag: 0b21998ef8ce86df97f278dd9fa6852779074c1b
