#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: f25bcd1edb3fb797817784288e5bf6d568c99c6c
  - name: quay.io/nexodus/envsubst
    newTag: f25bcd1edb3fb797817784288e5bf6d568c99c6c
  - name: quay.io/nexodus/frontend
    newTag: f25bcd1edb3fb797817784288e5bf6d568c99c6c
  - name: quay.io/nexodus/go-ipam
    newTag: f25bcd1edb3fb797817784288e5bf6d568c99c6c
