#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 0cde03936f906b93211a0f58c626add96b0e5836
  - name: quay.io/nexodus/envsubst
    newTag: 0cde03936f906b93211a0f58c626add96b0e5836
  - name: quay.io/nexodus/frontend
    newTag: 0cde03936f906b93211a0f58c626add96b0e5836
  - name: quay.io/nexodus/go-ipam
    newTag: 0cde03936f906b93211a0f58c626add96b0e5836
