#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 1f2811e3bd073988c2ec5b73c51c249589084a1a
  - name: quay.io/nexodus/envsubst
    newTag: 1f2811e3bd073988c2ec5b73c51c249589084a1a
  - name: quay.io/nexodus/frontend
    newTag: 1f2811e3bd073988c2ec5b73c51c249589084a1a
  - name: quay.io/nexodus/go-ipam
    newTag: 1f2811e3bd073988c2ec5b73c51c249589084a1a
