#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 84c85611d31ad7eb35449079143d64cfc97616fa
  - name: quay.io/nexodus/envsubst
    newTag: 84c85611d31ad7eb35449079143d64cfc97616fa
  - name: quay.io/nexodus/frontend
    newTag: 84c85611d31ad7eb35449079143d64cfc97616fa
  - name: quay.io/nexodus/go-ipam
    newTag: 84c85611d31ad7eb35449079143d64cfc97616fa
