#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: d097bef5c60161ff6814e9b7344bda2a771725ba
  - name: quay.io/nexodus/envsubst
    newTag: d097bef5c60161ff6814e9b7344bda2a771725ba
  - name: quay.io/nexodus/frontend
    newTag: d097bef5c60161ff6814e9b7344bda2a771725ba
  - name: quay.io/nexodus/go-ipam
    newTag: d097bef5c60161ff6814e9b7344bda2a771725ba
