#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 3040cd5c625bd1f5928b8e4ea4a1b3d8bebad7b5
  - name: quay.io/nexodus/envsubst
    newTag: 3040cd5c625bd1f5928b8e4ea4a1b3d8bebad7b5
  - name: quay.io/nexodus/frontend
    newTag: 3040cd5c625bd1f5928b8e4ea4a1b3d8bebad7b5
  - name: quay.io/nexodus/go-ipam
    newTag: 3040cd5c625bd1f5928b8e4ea4a1b3d8bebad7b5
