#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: 4e51faaefa1c044534dc6b493f11f905e1dcc957
  - name: quay.io/nexodus/envsubst
    newTag: 4e51faaefa1c044534dc6b493f11f905e1dcc957
  - name: quay.io/nexodus/frontend
    newTag: 4e51faaefa1c044534dc6b493f11f905e1dcc957
  - name: quay.io/nexodus/go-ipam
    newTag: 4e51faaefa1c044534dc6b493f11f905e1dcc957
