#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: ef07f062e7d1715594ca17b114eb95d9869e027c
  - name: quay.io/nexodus/envsubst
    newTag: ef07f062e7d1715594ca17b114eb95d9869e027c
  - name: quay.io/nexodus/frontend
    newTag: ef07f062e7d1715594ca17b114eb95d9869e027c
  - name: quay.io/nexodus/go-ipam
    newTag: ef07f062e7d1715594ca17b114eb95d9869e027c
