#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 78983d716122eb12805bf94157b133d92f7a2924
  - name: quay.io/nexodus/envsubst
    newTag: 78983d716122eb12805bf94157b133d92f7a2924
  - name: quay.io/nexodus/frontend
    newTag: 78983d716122eb12805bf94157b133d92f7a2924
  - name: quay.io/nexodus/go-ipam
    newTag: 78983d716122eb12805bf94157b133d92f7a2924
