#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: bab0334e273c98d18f0b7bbe58b45c13bfd68ca4
  - name: quay.io/nexodus/envsubst
    newTag: bab0334e273c98d18f0b7bbe58b45c13bfd68ca4
  - name: quay.io/nexodus/frontend
    newTag: bab0334e273c98d18f0b7bbe58b45c13bfd68ca4
  - name: quay.io/nexodus/go-ipam
    newTag: bab0334e273c98d18f0b7bbe58b45c13bfd68ca4
