#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 81ef63a57fc3f1862a4085095232ef9a791dcb64
  - name: quay.io/nexodus/envsubst
    newTag: 81ef63a57fc3f1862a4085095232ef9a791dcb64
  - name: quay.io/nexodus/frontend
    newTag: 81ef63a57fc3f1862a4085095232ef9a791dcb64
  - name: quay.io/nexodus/go-ipam
    newTag: 81ef63a57fc3f1862a4085095232ef9a791dcb64
