#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: ebc31df2d58c2cde683f17fbff315ac87ac1fc11
  - name: quay.io/nexodus/envsubst
    newTag: ebc31df2d58c2cde683f17fbff315ac87ac1fc11
  - name: quay.io/nexodus/frontend
    newTag: ebc31df2d58c2cde683f17fbff315ac87ac1fc11
  - name: quay.io/nexodus/go-ipam
    newTag: ebc31df2d58c2cde683f17fbff315ac87ac1fc11
