#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 5f36de67c37375b9fbb2ac39135aa0bc071df83f
  - name: quay.io/nexodus/envsubst
    newTag: 5f36de67c37375b9fbb2ac39135aa0bc071df83f
  - name: quay.io/nexodus/frontend
    newTag: 5f36de67c37375b9fbb2ac39135aa0bc071df83f
  - name: quay.io/nexodus/go-ipam
    newTag: 5f36de67c37375b9fbb2ac39135aa0bc071df83f
