#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 0137902520ab2be364106cd82a040f39125cdda4
  - name: quay.io/nexodus/envsubst
    newTag: 0137902520ab2be364106cd82a040f39125cdda4
  - name: quay.io/nexodus/frontend
    newTag: 0137902520ab2be364106cd82a040f39125cdda4
  - name: quay.io/nexodus/go-ipam
    newTag: 0137902520ab2be364106cd82a040f39125cdda4
