#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: eec9f3507462b3054b50e301650775909dae34da
  - name: quay.io/nexodus/envsubst
    newTag: eec9f3507462b3054b50e301650775909dae34da
  - name: quay.io/nexodus/frontend
    newTag: eec9f3507462b3054b50e301650775909dae34da
  - name: quay.io/nexodus/go-ipam
    newTag: eec9f3507462b3054b50e301650775909dae34da
