#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: 9a77b30e637b7882cd28a1a4e7f5e26c30416ca1
  - name: quay.io/nexodus/envsubst
    newTag: 9a77b30e637b7882cd28a1a4e7f5e26c30416ca1
  - name: quay.io/nexodus/frontend
    newTag: 9a77b30e637b7882cd28a1a4e7f5e26c30416ca1
  - name: quay.io/nexodus/go-ipam
    newTag: 9a77b30e637b7882cd28a1a4e7f5e26c30416ca1
