#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: 536ed2cc0633f36ade42fa6c36c4099880f33395
  - name: quay.io/nexodus/envsubst
    newTag: 536ed2cc0633f36ade42fa6c36c4099880f33395
  - name: quay.io/nexodus/frontend
    newTag: 536ed2cc0633f36ade42fa6c36c4099880f33395
  - name: quay.io/nexodus/go-ipam
    newTag: 536ed2cc0633f36ade42fa6c36c4099880f33395
