#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 42247967a2f31e9e664cb8e70e6669749ae04049
  - name: quay.io/nexodus/envsubst
    newTag: 42247967a2f31e9e664cb8e70e6669749ae04049
  - name: quay.io/nexodus/frontend
    newTag: 42247967a2f31e9e664cb8e70e6669749ae04049
  - name: quay.io/nexodus/go-ipam
    newTag: 42247967a2f31e9e664cb8e70e6669749ae04049
