#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: 230940bbe43094cddf8542929951efd2873475df
  - name: quay.io/nexodus/envsubst
    newTag: 230940bbe43094cddf8542929951efd2873475df
  - name: quay.io/nexodus/frontend
    newTag: 230940bbe43094cddf8542929951efd2873475df
  - name: quay.io/nexodus/go-ipam
    newTag: 230940bbe43094cddf8542929951efd2873475df
