#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 777f47369b286e2c938c4e3365438752054d563e
  - name: quay.io/nexodus/envsubst
    newTag: 777f47369b286e2c938c4e3365438752054d563e
  - name: quay.io/nexodus/frontend
    newTag: 777f47369b286e2c938c4e3365438752054d563e
  - name: quay.io/nexodus/go-ipam
    newTag: 777f47369b286e2c938c4e3365438752054d563e
