#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: fc78db20b376efa3d5dfe5b7c4735fa9afa3a3d8
  - name: quay.io/nexodus/envsubst
    newTag: fc78db20b376efa3d5dfe5b7c4735fa9afa3a3d8
  - name: quay.io/nexodus/frontend
    newTag: fc78db20b376efa3d5dfe5b7c4735fa9afa3a3d8
  - name: quay.io/nexodus/go-ipam
    newTag: fc78db20b376efa3d5dfe5b7c4735fa9afa3a3d8
