#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: 43841cbd933fa43be500962a1ac141b1c21509f3
  - name: quay.io/nexodus/envsubst
    newTag: 43841cbd933fa43be500962a1ac141b1c21509f3
  - name: quay.io/nexodus/frontend
    newTag: 43841cbd933fa43be500962a1ac141b1c21509f3
  - name: quay.io/nexodus/go-ipam
    newTag: 43841cbd933fa43be500962a1ac141b1c21509f3
