#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: cb599dad0b3bac5aedef04884b77757fb509689a
  - name: quay.io/nexodus/envsubst
    newTag: cb599dad0b3bac5aedef04884b77757fb509689a
  - name: quay.io/nexodus/frontend
    newTag: cb599dad0b3bac5aedef04884b77757fb509689a
  - name: quay.io/nexodus/go-ipam
    newTag: cb599dad0b3bac5aedef04884b77757fb509689a
