#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 79df2ca4f3a1b0ce3cfb11b563a82d2c8c52b917
  - name: quay.io/nexodus/envsubst
    newTag: 79df2ca4f3a1b0ce3cfb11b563a82d2c8c52b917
  - name: quay.io/nexodus/frontend
    newTag: 79df2ca4f3a1b0ce3cfb11b563a82d2c8c52b917
  - name: quay.io/nexodus/go-ipam
    newTag: 79df2ca4f3a1b0ce3cfb11b563a82d2c8c52b917
