#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 396a6addefa36a91ba442a381bc7143a52c05721
  - name: quay.io/nexodus/envsubst
    newTag: 396a6addefa36a91ba442a381bc7143a52c05721
  - name: quay.io/nexodus/frontend
    newTag: 396a6addefa36a91ba442a381bc7143a52c05721
  - name: quay.io/nexodus/go-ipam
    newTag: 396a6addefa36a91ba442a381bc7143a52c05721
