#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: f3a48e50e1a8c98951c5941ace730c1e57e6601d
  - name: quay.io/nexodus/envsubst
    newTag: f3a48e50e1a8c98951c5941ace730c1e57e6601d
  - name: quay.io/nexodus/frontend
    newTag: f3a48e50e1a8c98951c5941ace730c1e57e6601d
  - name: quay.io/nexodus/go-ipam
    newTag: f3a48e50e1a8c98951c5941ace730c1e57e6601d
