#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 08e1677b2e92c05c9805a1175e1ff9e786e744e4
  - name: quay.io/nexodus/envsubst
    newTag: 08e1677b2e92c05c9805a1175e1ff9e786e744e4
  - name: quay.io/nexodus/frontend
    newTag: 08e1677b2e92c05c9805a1175e1ff9e786e744e4
  - name: quay.io/nexodus/go-ipam
    newTag: 08e1677b2e92c05c9805a1175e1ff9e786e744e4
