#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 6d4f5b4be54ec3252a080875ac04942e2c41511b
  - name: quay.io/nexodus/envsubst
    newTag: 6d4f5b4be54ec3252a080875ac04942e2c41511b
  - name: quay.io/nexodus/frontend
    newTag: 6d4f5b4be54ec3252a080875ac04942e2c41511b
  - name: quay.io/nexodus/go-ipam
    newTag: 6d4f5b4be54ec3252a080875ac04942e2c41511b
