#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 5605cfb834b8d37d40d324c3c8626d293754bbf4
  - name: quay.io/nexodus/envsubst
    newTag: 5605cfb834b8d37d40d324c3c8626d293754bbf4
  - name: quay.io/nexodus/frontend
    newTag: 5605cfb834b8d37d40d324c3c8626d293754bbf4
  - name: quay.io/nexodus/go-ipam
    newTag: 5605cfb834b8d37d40d324c3c8626d293754bbf4
