#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: d455afcad6f01a5baab35f5fa3bf2b28b227bbff
  - name: quay.io/nexodus/envsubst
    newTag: d455afcad6f01a5baab35f5fa3bf2b28b227bbff
  - name: quay.io/nexodus/frontend
    newTag: d455afcad6f01a5baab35f5fa3bf2b28b227bbff
  - name: quay.io/nexodus/go-ipam
    newTag: d455afcad6f01a5baab35f5fa3bf2b28b227bbff
