#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 2f1cf94d1ada959fe00ad2a9bf2ebfc7f772a420
  - name: quay.io/nexodus/envsubst
    newTag: 2f1cf94d1ada959fe00ad2a9bf2ebfc7f772a420
  - name: quay.io/nexodus/frontend
    newTag: 2f1cf94d1ada959fe00ad2a9bf2ebfc7f772a420
  - name: quay.io/nexodus/go-ipam
    newTag: 2f1cf94d1ada959fe00ad2a9bf2ebfc7f772a420
