#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 0c88aa1ac9b8ef80f32061c630d69c81d8410663
  - name: quay.io/nexodus/envsubst
    newTag: 0c88aa1ac9b8ef80f32061c630d69c81d8410663
  - name: quay.io/nexodus/frontend
    newTag: 0c88aa1ac9b8ef80f32061c630d69c81d8410663
  - name: quay.io/nexodus/go-ipam
    newTag: 0c88aa1ac9b8ef80f32061c630d69c81d8410663
