#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  # - ../../components/monitoring
  - ../../components/limitador
# patchesJson6902:
#   - patch: |-
#       - op: replace
#         path: /data/NEXAPI_TRACE_ENDPOINT_OTLP
#         value: jaeger-collector:4317
#       - op: replace
#         path: /data/NEXAPI_TRACE_INSECURE
#         value: "1"
#     target:
#       kind: ConfigMap
#       name: apiserver
#       namespace: nexodus
images:
  - name: quay.io/nexodus/apiserver
    newTag: a5bd3e3696c930615a1cea4cdd31851b8a57944f
  - name: quay.io/nexodus/envsubst
    newTag: a5bd3e3696c930615a1cea4cdd31851b8a57944f
  - name: quay.io/nexodus/frontend
    newTag: a5bd3e3696c930615a1cea4cdd31851b8a57944f
  - name: quay.io/nexodus/go-ipam
    newTag: a5bd3e3696c930615a1cea4cdd31851b8a57944f
