#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: 3e94b4858109c45a0c57c5c71a4c527ac7621ddb
  - name: quay.io/nexodus/envsubst
    newTag: 3e94b4858109c45a0c57c5c71a4c527ac7621ddb
  - name: quay.io/nexodus/frontend
    newTag: 3e94b4858109c45a0c57c5c71a4c527ac7621ddb
  - name: quay.io/nexodus/go-ipam
    newTag: 3e94b4858109c45a0c57c5c71a4c527ac7621ddb
