#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 64a9cfaf8714b24a6a05bb4089dea6379d2c8643
  - name: quay.io/nexodus/envsubst
    newTag: 64a9cfaf8714b24a6a05bb4089dea6379d2c8643
  - name: quay.io/nexodus/frontend
    newTag: 64a9cfaf8714b24a6a05bb4089dea6379d2c8643
  - name: quay.io/nexodus/go-ipam
    newTag: 64a9cfaf8714b24a6a05bb4089dea6379d2c8643
