#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: dcce9400f31c8218f2c6220690a4c068d7271546
  - name: quay.io/nexodus/envsubst
    newTag: dcce9400f31c8218f2c6220690a4c068d7271546
  - name: quay.io/nexodus/frontend
    newTag: dcce9400f31c8218f2c6220690a4c068d7271546
  - name: quay.io/nexodus/go-ipam
    newTag: dcce9400f31c8218f2c6220690a4c068d7271546
