#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: ac5c7bd14dc70bc61a01afa12d21dc938a40351b
  - name: quay.io/nexodus/envsubst
    newTag: ac5c7bd14dc70bc61a01afa12d21dc938a40351b
  - name: quay.io/nexodus/frontend
    newTag: ac5c7bd14dc70bc61a01afa12d21dc938a40351b
  - name: quay.io/nexodus/go-ipam
    newTag: ac5c7bd14dc70bc61a01afa12d21dc938a40351b
