#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: d57f7b27491cf07a381b85910832c2c12f8eca93
  - name: quay.io/nexodus/envsubst
    newTag: d57f7b27491cf07a381b85910832c2c12f8eca93
  - name: quay.io/nexodus/frontend
    newTag: d57f7b27491cf07a381b85910832c2c12f8eca93
  - name: quay.io/nexodus/go-ipam
    newTag: d57f7b27491cf07a381b85910832c2c12f8eca93
