#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 6fe0a85190c868ed264fc725c683624d50735387
  - name: quay.io/nexodus/envsubst
    newTag: 6fe0a85190c868ed264fc725c683624d50735387
  - name: quay.io/nexodus/frontend
    newTag: 6fe0a85190c868ed264fc725c683624d50735387
  - name: quay.io/nexodus/go-ipam
    newTag: 6fe0a85190c868ed264fc725c683624d50735387
