#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: af4f7fbd3825280f787d9dc5653c00121963b439
  - name: quay.io/nexodus/envsubst
    newTag: af4f7fbd3825280f787d9dc5653c00121963b439
  - name: quay.io/nexodus/frontend
    newTag: af4f7fbd3825280f787d9dc5653c00121963b439
  - name: quay.io/nexodus/go-ipam
    newTag: af4f7fbd3825280f787d9dc5653c00121963b439
