#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: ae882aea767380e192263284515e2d3a22239684
  - name: quay.io/nexodus/envsubst
    newTag: ae882aea767380e192263284515e2d3a22239684
  - name: quay.io/nexodus/frontend
    newTag: ae882aea767380e192263284515e2d3a22239684
  - name: quay.io/nexodus/go-ipam
    newTag: ae882aea767380e192263284515e2d3a22239684
