#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: 7263519478f60f15a34f9bb8687790d85b580d8f
  - name: quay.io/nexodus/envsubst
    newTag: 7263519478f60f15a34f9bb8687790d85b580d8f
  - name: quay.io/nexodus/frontend
    newTag: 7263519478f60f15a34f9bb8687790d85b580d8f
  - name: quay.io/nexodus/go-ipam
    newTag: 7263519478f60f15a34f9bb8687790d85b580d8f
