#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: dab5bfa889dceb64636947e5a71327e3df16060b
  - name: quay.io/nexodus/envsubst
    newTag: dab5bfa889dceb64636947e5a71327e3df16060b
  - name: quay.io/nexodus/frontend
    newTag: dab5bfa889dceb64636947e5a71327e3df16060b
  - name: quay.io/nexodus/go-ipam
    newTag: dab5bfa889dceb64636947e5a71327e3df16060b
