#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: b441045de99a6cc5c02e132f5dd0b9de570285f5
  - name: quay.io/nexodus/envsubst
    newTag: b441045de99a6cc5c02e132f5dd0b9de570285f5
  - name: quay.io/nexodus/frontend
    newTag: b441045de99a6cc5c02e132f5dd0b9de570285f5
  - name: quay.io/nexodus/go-ipam
    newTag: b441045de99a6cc5c02e132f5dd0b9de570285f5
