#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: e26f4802fff9afaac4e0269b4592c172633e06de
  - name: quay.io/nexodus/envsubst
    newTag: e26f4802fff9afaac4e0269b4592c172633e06de
  - name: quay.io/nexodus/frontend
    newTag: e26f4802fff9afaac4e0269b4592c172633e06de
  - name: quay.io/nexodus/go-ipam
    newTag: e26f4802fff9afaac4e0269b4592c172633e06de
