#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 05bda9b5b9e8a61927811c02d2cc9a0d9a04b0a4
  - name: quay.io/nexodus/envsubst
    newTag: 05bda9b5b9e8a61927811c02d2cc9a0d9a04b0a4
  - name: quay.io/nexodus/frontend
    newTag: 05bda9b5b9e8a61927811c02d2cc9a0d9a04b0a4
  - name: quay.io/nexodus/go-ipam
    newTag: 05bda9b5b9e8a61927811c02d2cc9a0d9a04b0a4
