#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
# - ../../components/monitoring
components:
  - ../../components/limitador
# patches:
#   - patch: |-
#       - op: replace
#         path: /data/NEXAPI_TRACE_ENDPOINT_OTLP
#         value: jaeger-collector:4317
#       - op: replace
#         path: /data/NEXAPI_TRACE_INSECURE
#         value: "1"
#     target:
#       kind: ConfigMap
#       name: apiserver
#       namespace: nexodus
images:
  - name: quay.io/nexodus/apiserver
    newTag: c76f249a5c576abc5a26ab288fbe46eac9c2f9e2
  - name: quay.io/nexodus/envsubst
    newTag: c76f249a5c576abc5a26ab288fbe46eac9c2f9e2
  - name: quay.io/nexodus/frontend
    newTag: c76f249a5c576abc5a26ab288fbe46eac9c2f9e2
  - name: quay.io/nexodus/go-ipam
    newTag: c76f249a5c576abc5a26ab288fbe46eac9c2f9e2
