#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 8ef6fae85f8dd237ea5651e46326f10f5690b102
  - name: quay.io/nexodus/envsubst
    newTag: 8ef6fae85f8dd237ea5651e46326f10f5690b102
  - name: quay.io/nexodus/frontend
    newTag: 8ef6fae85f8dd237ea5651e46326f10f5690b102
  - name: quay.io/nexodus/go-ipam
    newTag: 8ef6fae85f8dd237ea5651e46326f10f5690b102
