#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 06107ef7c2c0dec468d97481e13219d817710b9d
  - name: quay.io/nexodus/envsubst
    newTag: 06107ef7c2c0dec468d97481e13219d817710b9d
  - name: quay.io/nexodus/frontend
    newTag: 06107ef7c2c0dec468d97481e13219d817710b9d
  - name: quay.io/nexodus/go-ipam
    newTag: 06107ef7c2c0dec468d97481e13219d817710b9d
