#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: cea97401571928c7e2a871c3fc761c246cadb3d3
  - name: quay.io/nexodus/envsubst
    newTag: cea97401571928c7e2a871c3fc761c246cadb3d3
  - name: quay.io/nexodus/frontend
    newTag: cea97401571928c7e2a871c3fc761c246cadb3d3
  - name: quay.io/nexodus/go-ipam
    newTag: cea97401571928c7e2a871c3fc761c246cadb3d3
