#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 166ee4778fb20ac15e66c337efe043cf04f7915f
  - name: quay.io/nexodus/envsubst
    newTag: 166ee4778fb20ac15e66c337efe043cf04f7915f
  - name: quay.io/nexodus/frontend
    newTag: 166ee4778fb20ac15e66c337efe043cf04f7915f
  - name: quay.io/nexodus/go-ipam
    newTag: 166ee4778fb20ac15e66c337efe043cf04f7915f
