#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: af7ba556dc4a234573dae9cd0707ad681c2334af
  - name: quay.io/nexodus/envsubst
    newTag: af7ba556dc4a234573dae9cd0707ad681c2334af
  - name: quay.io/nexodus/frontend
    newTag: af7ba556dc4a234573dae9cd0707ad681c2334af
  - name: quay.io/nexodus/go-ipam
    newTag: af7ba556dc4a234573dae9cd0707ad681c2334af
