#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 2ff8596ec4c940c1eb2107dfcdb9f3402252403e
  - name: quay.io/nexodus/envsubst
    newTag: 2ff8596ec4c940c1eb2107dfcdb9f3402252403e
  - name: quay.io/nexodus/frontend
    newTag: 2ff8596ec4c940c1eb2107dfcdb9f3402252403e
  - name: quay.io/nexodus/go-ipam
    newTag: 2ff8596ec4c940c1eb2107dfcdb9f3402252403e
