#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
# - ../../components/monitoring
components:
  - ../../components/limitador
# patches:
#   - patch: |-
#       - op: replace
#         path: /data/NEXAPI_TRACE_ENDPOINT_OTLP
#         value: jaeger-collector:4317
#       - op: replace
#         path: /data/NEXAPI_TRACE_INSECURE
#         value: "1"
#     target:
#       kind: ConfigMap
#       name: apiserver
#       namespace: nexodus
images:
  - name: quay.io/nexodus/apiserver
    newTag: 89bfe136a51cb6cb755d38c19eff83ee526d9b5d
  - name: quay.io/nexodus/envsubst
    newTag: 89bfe136a51cb6cb755d38c19eff83ee526d9b5d
  - name: quay.io/nexodus/frontend
    newTag: 89bfe136a51cb6cb755d38c19eff83ee526d9b5d
  - name: quay.io/nexodus/go-ipam
    newTag: 89bfe136a51cb6cb755d38c19eff83ee526d9b5d
