#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: ecd957275c867d8532bdabb69d9ea24f521f2902
  - name: quay.io/nexodus/envsubst
    newTag: ecd957275c867d8532bdabb69d9ea24f521f2902
  - name: quay.io/nexodus/frontend
    newTag: ecd957275c867d8532bdabb69d9ea24f521f2902
  - name: quay.io/nexodus/go-ipam
    newTag: ecd957275c867d8532bdabb69d9ea24f521f2902
