#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: quay.io/nexodus/apiserver
    newTag: 2ac950dc3c256e05318bd1545238f4cca259191c
  - name: quay.io/nexodus/envsubst
    newTag: 2ac950dc3c256e05318bd1545238f4cca259191c
  - name: quay.io/nexodus/frontend
    newTag: 2ac950dc3c256e05318bd1545238f4cca259191c
  - name: quay.io/nexodus/go-ipam
    newTag: 2ac950dc3c256e05318bd1545238f4cca259191c
