#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 128318c2a88a3ee3f38e7fdf5899120e64b34110
  - name: quay.io/nexodus/envsubst
    newTag: 128318c2a88a3ee3f38e7fdf5899120e64b34110
  - name: quay.io/nexodus/frontend
    newTag: 128318c2a88a3ee3f38e7fdf5899120e64b34110
  - name: quay.io/nexodus/go-ipam
    newTag: 128318c2a88a3ee3f38e7fdf5899120e64b34110
