#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: d3739513a65f8f3393602c348c940b78c934c804
  - name: quay.io/nexodus/envsubst
    newTag: d3739513a65f8f3393602c348c940b78c934c804
  - name: quay.io/nexodus/frontend
    newTag: d3739513a65f8f3393602c348c940b78c934c804
  - name: quay.io/nexodus/go-ipam
    newTag: d3739513a65f8f3393602c348c940b78c934c804
