#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 7b96ca342205686f8e3e26d17a8f95c3bbfe3399
  - name: quay.io/nexodus/envsubst
    newTag: 7b96ca342205686f8e3e26d17a8f95c3bbfe3399
  - name: quay.io/nexodus/frontend
    newTag: 7b96ca342205686f8e3e26d17a8f95c3bbfe3399
  - name: quay.io/nexodus/go-ipam
    newTag: 7b96ca342205686f8e3e26d17a8f95c3bbfe3399
