#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: ef23d395e1facf16a5c92e092c5fcb2ae9dae1a0
  - name: quay.io/nexodus/envsubst
    newTag: ef23d395e1facf16a5c92e092c5fcb2ae9dae1a0
  - name: quay.io/nexodus/frontend
    newTag: ef23d395e1facf16a5c92e092c5fcb2ae9dae1a0
  - name: quay.io/nexodus/go-ipam
    newTag: ef23d395e1facf16a5c92e092c5fcb2ae9dae1a0
