#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: 03d0305530b5325d648999b4c82e94ebba508a95
  - name: quay.io/nexodus/envsubst
    newTag: 03d0305530b5325d648999b4c82e94ebba508a95
  - name: quay.io/nexodus/frontend
    newTag: 03d0305530b5325d648999b4c82e94ebba508a95
  - name: quay.io/nexodus/go-ipam
    newTag: 03d0305530b5325d648999b4c82e94ebba508a95
