#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: e3d4687a99af9866b9f0516aced7fcfcd77b06d7
  - name: quay.io/nexodus/envsubst
    newTag: e3d4687a99af9866b9f0516aced7fcfcd77b06d7
  - name: quay.io/nexodus/frontend
    newTag: e3d4687a99af9866b9f0516aced7fcfcd77b06d7
  - name: quay.io/nexodus/go-ipam
    newTag: e3d4687a99af9866b9f0516aced7fcfcd77b06d7
