#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: a01b153438cdab4ae556d3ad12566a5f30954bd3
  - name: quay.io/nexodus/envsubst
    newTag: a01b153438cdab4ae556d3ad12566a5f30954bd3
  - name: quay.io/nexodus/frontend
    newTag: a01b153438cdab4ae556d3ad12566a5f30954bd3
  - name: quay.io/nexodus/go-ipam
    newTag: a01b153438cdab4ae556d3ad12566a5f30954bd3
