#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 232f8d336370fb09cc9f1c9e4b346278ca376c07
  - name: quay.io/nexodus/envsubst
    newTag: 232f8d336370fb09cc9f1c9e4b346278ca376c07
  - name: quay.io/nexodus/frontend
    newTag: 232f8d336370fb09cc9f1c9e4b346278ca376c07
  - name: quay.io/nexodus/go-ipam
    newTag: 232f8d336370fb09cc9f1c9e4b346278ca376c07
