apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - issuer.yaml
  - serviceaccount.yaml
namespace: nexodus
components:
  - ../../components/limitador
configMapGenerator:
  - behavior: replace
    name: auth-config
    literals:
      - hostname=auth.try.nexodus.io
      - frontend-url=https://try.nexodus.io
  - behavior: replace
    name: realm
    files:
      - files/nexodus.json
  - behavior: merge
    name: apiproxy
    literals:
      - APIPROXY_OIDC_URL=https://auth.try.nexodus.io/realms/nexodus
      - APIPROXY_API_DOMAIN=api.try.nexodus.io
      - APIPROXY_WEB_DOMAIN=try.nexodus.io
      - APIPROXY_WEB_ORIGINS=https://try.nexodus.io
  - behavior: merge
    name: apiserver
    literals:
      - NEXAPI_OIDC_URL=https://auth.try.nexodus.io/realms/nexodus
      - NEXAPI_DOMAIN=api.try.nexodus.io
      - NEXAPI_REDIRECT_URL=https://try.nexodus.io/#/login
      - NEXAPI_ORIGINS=https://try.nexodus.io

patchesJson6902:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.try.nexodus.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.try.nexodus.io
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: apiproxy
  - patch: |-
      - op: add
        path: /spec/template/spec/serviceAccountName
        value: nexodus-serviceaccount
    target:
      kind: Deployment
      name: apiproxy
  - patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
      - op: remove
        path: /metadata/annotations/nginx.ingress.kubernetes.io~1ssl-passthrough
      - op: replace
        path: /spec/rules/0/host
        value: auth.try.nexodus.io
      - op: replace
        path: /spec/rules/0/http/paths/0/pathType
        value: ImplementationSpecific
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: ''
    target:
      kind: Ingress
      name: auth
  - patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: auth.try.nexodus.io
      - op: replace
        path: /spec/issuerRef/name
        value: letsencrypt
    target:
      kind: Certificate
      name: nexodus-auth-cert
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: try.nexodus.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: try.nexodus.io
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: frontend
images:
  - name: quay.io/nexodus/apiserver
    newTag: 27cf4ae4833175c03a9244b13b091ba9af06e12c
  - name: quay.io/nexodus/envsubst
    newTag: 27cf4ae4833175c03a9244b13b091ba9af06e12c
  - name: quay.io/nexodus/frontend
    newTag: 27cf4ae4833175c03a9244b13b091ba9af06e12c
  - name: quay.io/nexodus/go-ipam
    newTag: 27cf4ae4833175c03a9244b13b091ba9af06e12c
