apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - image: docker.io/grafana/tempo:2.1.1
          args:
            - -config.file=/etc/tempo/tempo.yaml
          name: tempo
          ports:
            - name: http
              containerPort: 3200
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 1
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: tempo-config
            items:
              - key: tempo.yaml
                path: tempo.yaml
