apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: tempo-config
    files:
      - files/tempo.yaml
resources:
  - deployment.yaml
  - service.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: tempo
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/name: tempo
