apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - daemonset.yaml
commonLabels:
  app.kubernetes.io/component: nexodus-client
  app.kubernetes.io/instance: nexodus-client
  app.kubernetes.io/name: nexodus-client
