server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317

compactor:
  compaction:
    block_retention: 1h

metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus-operated:9090/api/v1/write
        send_exemplars: true

storage:
  trace:
    backend: s3
    wal:
      path: /tmp/tempo/wal
    s3:
      bucket: tempo
      endpoint: minio:9000
      access_key: minio
      secret_key: supersecret
      insecure: true

overrides:
  metrics_generator_processors: [service-graphs, span-metrics]
