---
# tasks file for start-nexodus-agent
- name: Kill any existing nexd process from previous runs
  become: yes
  shell: |
    sudo killall nexd 2> /dev/null
  ignore_errors: yes

- name: Attach the Node Agent to the Controller
  become: yes
  shell: |
    nexd \
    --username '{{ nexodus_auth_uid }}' \
     s--password '{{ nexodus_auth_password }}' \
    {{ nexodus_url }} > nexodus-logs.txt 2>&1 &
