apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: promtail-rolebinding
  labels:
    app.kubernetes.io/component: promtail
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/name: promtail
subjects:
  - kind: ServiceAccount
    name: promtail-serviceaccount
roleRef:
  kind: Role
  name: promtail-role
  apiGroup: rbac.authorization.k8s.io
