apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: promtail-role
  labels:
    app.kubernetes.io/component: promtail
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/name: promtail
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - pods
    verbs:
      - get
      - watch
      - list
