apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail-serviceaccount
  labels:
    app.kubernetes.io/component: promtail
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/name: promtail
