apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  labels:
    app.kubernetes.io/component: promtail
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/name: promtail
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: promtail
      app.kubernetes.io/instance: promtail
      app.kubernetes.io/name: promtail
  template:
    metadata:
      labels:
        app.kubernetes.io/component: promtail
        app.kubernetes.io/instance: promtail
        app.kubernetes.io/name: promtail
    spec:
      serviceAccountName: promtail-serviceaccount
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: promtail
              app.kubernetes.io/instance: promtail
              app.kubernetes.io/name: promtail
      containers:
        - name: promtail-container
          image: docker.io/grafana/promtail:2.8.2
          args:
            - -config.file=/etc/promtail/promtail.yaml
          env:
            - name: "HOSTNAME"  # needed when using kubernetes_sd_configs
              valueFrom:
                fieldRef:
                  fieldPath: "spec.nodeName"
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail
              readOnly: true
            - name: pod-logs
              mountPath: /var/log/pods
              readOnly: true
      volumes:
        - name: promtail-config
          configMap:
            name: promtail-config
        - name: pod-logs
          hostPath:
            path: /var/log/pods
            type: Directory
