---
# tasks file for stop-nexodus-agent
- name: Kill any existing nexd process from previous runs
  become: yes
  shell: |
    sudo killall nexd 2> /dev/null
  ignore_errors: yes

- name: Delete wg0
  become: yes
  shell: |
    sudo ip link del wg0
  ignore_errors: yes
