name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.2.2
      with:
        BANNED_LABELS: "hold"
        BANNED_LABELS_DESCRIPTION: "PR may not merge with ${bannedLabel.name} label."