name: promote

concurrency: prod-${{ github.ref_name }}

on:
  workflow_call:
  workflow_dispatch:

jobs:
  update-prod:
    name: Update Production Deployment
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the qa Tag
        uses: actions/checkout@v3
        with:
          ref: "qa"

      - name: Promote to the prod Tag
        shell: bash
        run: |
          echo Promoting qa ($(git rev-parse HEAD)) to prod
          git tag prod --force
          git push origin prod --force 

#        id: "prodtag"
#        uses: rickstaa/action-create-tag@v1
#        with:
#          tag: "prod"
#          tag_exists_error: false
#          force_push_tag: true