name: promote

concurrency: prod-${{ github.ref_name }}

on:
  workflow_call:
  workflow_dispatch:

jobs:
  update-prod:
    name: Update Production Deployment
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Tag the prod release
        id: "prodtag"
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "prod"
          tag_exists_error: false
          force_push_tag: true