apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: nexodus
  namespace: nexodus
spec:
  params:
    - description: The quay image repository url
      name: image-repo-url
    - default: latest
      description: Recently updated image tag
      name: image-updated-tags
    - description: The quay repository name
      name: image-repo-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: deploy-nexodus-
      spec:
        pipelineRef:
          name: deploy-nexodus
        serviceAccountName: pipeline
        workspaces:
          - emptyDir: {}
            name: shared-workspace
